# specific configuration options for production environment
# that overrides the default ones
production:
  email_delivery:
     delivery_method: :smtp
     smtp_settings:
       tls: true
       enable_starttls_auto: true
       address: "smtp.gmail.com"
       port: '587'
       domain: "gmail.com"
       authentication: :plain
       user_name: ENV["EMAIL_USERNAME"]
       password: ENV["EMAIL_PASWD"]

